email: ""
raw_directory: "testdata"
sample_table: "testdata/samples.small.tsv"
do_primers: true
do_dada: true
do_taxonomy: false
do_postprocessing: true
primers:
  fwd: 
    sequence: GTGYCAGCMGCCGCGGTAA
    name: 515F
  rvs: 
    sequence: GGACTACNVGGGTWTCTAAT
    name: 806R
paired: true
dada:
  pool: false
sequencing_direction: "unknown"
filtering:
  trunc_length:
    fwd: 170
    rvs: 130
  trunc_qual: 
    fwd: 13
    rvs: 13
  max_EE:
    fwd: 0.2
    rvs: 0.2
  minLen:
    fwd: 100
    rvs: 100
  maxLen:
    fwd: Inf
    rvs: Inf
  minQ:
    fwd: 0
    rvs: 0
downsampling:
  do: true
  number: 1000
tmp_dir: "tmp"
outputdir: "testoutput"
final_table_filtering:
  do: false
hand_off:
  biom: true
  phyloseq: true
