email: ""
raw_directory: "/work/$USER"
sample_table: "/work/$USER/samples.tsv"
outputdir: "/work/$USER/outputITS"
do_primers: true
do_dada: true
do_taxonomy: true
do_postprocessing: true
taxonomy:
  decipher:
    do: false
  mothur:
    do: true
    post_ITSx: true
    db_path: "../DBs/amplicon"
    tax_db: "unite_8.2_fungi.ITS2"
primers:
  fwd: 
    sequence: TCCTCCGCTTATTGATATGC
    name: ITS4
  rvs: 
    sequence: GTGARTCATCGAATCTTTG
    name: fITS7
paired: true
sequencing_direction: "unknown"
primer_cutting:
  overlap: 10
  count: 2
  filter_if_not_match: any
  perc_mismatch: 0.2
  indels: "--no-indels"
filtering:
  trunc_length:
    fwd: 0
    rvs: 0
  trunc_qual: 
    fwd: 15
    rvs: 15
  max_EE:
    fwd: 3
    rvs: 3
  minLen:
    fwd: 70
    rvs: 70
  maxLen:
    fwd: Inf
    rvs: Inf
  minQ:
    fwd: 0
    rvs: 0
pair_merging:
  min_overlap: 20
  max_mismatch: 2
chimeras:
  remove: true
  method: consensus
blast:
  do: false
  e_val: 0.00001
ITSx:
  do: true
  min_regions: 1
  region: ITS2
  e_val: 1e-5
hand_off:
  biom: true
  phyloseq: false
final_table_filtering:
  do: true
  keep_target_taxa: "Fungi"
postprocessing:
  rarefaction_curve: true
  funguild:
    do: false
    funguild_db: "../DBs/amplicon/funguild_db.json"
    classifier: mothur
  fungalTraits:
    do: false
    db: "../DBs/functions/FungalTraits_1.2_ver_16Dec_2020_V.1.2.tsv"
    classifier: mothur
    level: "Genus"
  treeing:
    do: false
