__default__: 
  call: "sbatch"
  mem_per_cpu: "--mem-per-cpu "
  partition: ""
  runtime: "-t"
  threads: "-c"
  stdout: "-o dadasnake.{rule}.{wildcards}.stdout"

fastqc_1:
  partition: "-n 1"

fastqc_filtered:
  partition: "-n 1"
