__default__: 
  call: "sbatch"
  mem_per_cpu: "--mem-per-cpu "
  partition: "-p batch"
  runtime: "-t"
  threads: "-c"
  stdout: "-o dadasnake.{rule}.{wildcards}.stdout"

dada_mergeruns:
  partition: "-p bigmem -q qos-bigmem"

mothur_taxonomy:
  partition: "-p bigmem -q qos-bigmem"

decipher_taxonomy:
  partition: "-p bigmem -q qos-bigmem"

mothur_taxonomy_postITSx:
  partition: "-p bigmem -q qos-bigmem"

blastn:
  partition: "-p bigmem -q qos-bigmem"

bigbiom_handoff_preTax:
  partition: "-p bigmem -q qos-bigmem"

bigphyloseq_handoff_preTax:
  partition: "-p bigmem -q qos-bigmem"

bigdada_mergeruns:
  partition: "-p bigmem -q qos-bigmem"

bignochime_numbers:
  partition: "-p bigmem -q qos-bigmem"

bigtabled_numbers:
  partition: "-p bigmem -q qos-bigmem"

bigrarefaction_curve_noFilter:
  partition: "-p bigmem -q qos-bigmem"

bigphyloseq_handoff_post:
  partition: "-p bigmem -q qos-bigmem"

bigphyloseq_handoff_postFilter:
  partition: "-p bigmem -q qos-bigmem"

bigtreeing_Filter_fasttreeMP:
  partition: "-p bigmem -q qos-bigmem"

bigtreeing_noFilter_fasttreeMP:
  partition: "-p bigmem -q qos-bigmem"

bigtreeing_noFilter:
  partition: "-p bigmem -q qos-bigmem"

bigtreeing_Filter:
  partition: "-p bigmem -q qos-bigmem"

bigmultiAlign_noFilter:
  partition: "-p bigmem -q qos-bigmem"

bigfiltering_table:
  partition: "-p bigmem -q qos-bigmem"

bigtable_filter_numbers:
  partition: "-p bigmem -q qos-bigmem"

bigrarefaction_curve_Filter:
  partition: "-p bigmem -q qos-bigmem"

bigtaxonomy_to_OTUtab:
  partition: "-p bigmem -q qos-bigmem"

bigdada_taxonomy:
  partition: "-p bigmem -q qos-bigmem"

bigdecipher_taxonomy:
  partition: "-p bigmem -q qos-bigmem"

bigmothur_taxonomy_postITSx:
  partition: "-p bigmem -q qos-bigmem"

bigprepare_blastn:
  partition: "-p bigmem -q qos-bigmem"

bigguilds_noFilter:
  partition: "-p bigmem -q qos-bigmem"

bigguilds_Filter:
  partition: "-p bigmem -q qos-bigmem"

bigbiom_handoff_tax:
  partition: "-p bigmem -q qos-bigmem"

bigphyloseq_handoff_tax:
  partition: "-p bigmem -q qos-bigmem"


